### PR TITLE
Implement syncing backups to remote filesystems

### PR DESCRIPTION
**Pull request by Eximius**

### CODE REVIEW

**Comment by doudou** [comment]
Hi @Eximius. I'm not using neither maintaining snapsync anymore - haven't been for a long while. I'd gladly give you commit rights if you'd like, as well as add you on rubygems so that you can publish the gem.

**Comment by Eximius** [comment]
@doudou That would be cool. This project (while a bit dead) seemed like the best snapper snapshot sync tool available, so would be awesome to resurrect it. :)

**Comment by doudou** [comment]
Do you have a handle on rubygems.org ?

**Comment by Eximius** [comment]
@doudou Could you send me the commit rights invite again, I missed the deadline (had sent you an email).

Also registered a handle on rubygems.org - https://rubygems.org/profiles/Eximius

**Comment by doudou** [comment]
Done and done ... sorry for the delay

**Pull request merged**
